// UNCOMMENT LINE WITH YOUR EDITOR TO USE IT
#define USE_VIM
// #define USE_NANO

// CHANGE MAXIMUM POLYGONS
#define MAXPOLYGONS 32

// DEFINE SCALE OF OBJECTS
#define OBJECTSCALE 50

// SETS THE RATIO OF HEIGHT VS WIDTH OF A CHARACTER
// IF AN OBJECT FILE'S X COMPONENTS ARE ONLY 0, w.ws_pixel MAY BE RETURNING 0
// IN THAT CASE CHANGE THIS TO AROUND 1.8f
#define MONOSPACEHEIGHTVWIDTH ((double)w.ws_xpixel/(double)w.ws_ypixel)
